/**
 * @kairo/tokens — build script
 *
 * Compiles tokens.json (single source of truth, RFC §20) into:
 *   1. tokens.css  — CSS custom properties (`:root`) + Tailwind v4 `@theme`
 *   2. tokens.ts   — typed TS constants for chart colors, JS-side values
 *
 * Run: npm run build -w @kairo/tokens   (tsx packages/tokens/src/build.ts)
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, '..', 'dist');
mkdirSync(outDir, { recursive: true });

type RawTokens = {
  primitives: Record<string, string>;
  semantic: Record<string, string>;
  spacing: Record<string, string>;
  type: Record<string, { size: string; lineHeight: string; face: string }>;
  motion: Record<string, string>;
  radius: Record<string, string>;
  shadow: Record<string, string>;
  dataGradient: string[];
};

const raw: RawTokens = JSON.parse(
  readFileSync(join(here, 'tokens.json'), 'utf-8'),
);

// --- Resolve semantic tokens to primitive hex values -----------------------
const primitives = raw.primitives;
const resolvePrimitive = (ref: string): string =>
  primitives[ref] ?? primitives[`kairo-${ref}`] ?? '';

const semanticHex: Record<string, string> = {};
for (const [name, ref] of Object.entries(raw.semantic)) {
  const hex = resolvePrimitive(ref as string);
  if (!hex) throw new Error(`semantic token "${name}" refs unknown primitive "${ref}"`);
  semanticHex[name] = hex;
}

// --- CSS custom properties --------------------------------------------------
const cssLines: string[] = [];
cssLines.push(':root {');
for (const [name, value] of Object.entries(primitives)) {
  cssLines.push(`  --${name}: ${value};`);
}
for (const [name, value] of Object.entries(semanticHex)) {
  cssLines.push(`  --${name}: ${value};`);
}
for (const [name, value] of Object.entries(raw.spacing)) {
  cssLines.push(`  --${name}: ${value};`);
}
for (const [name, value] of Object.entries(raw.motion)) {
  cssLines.push(`  --${name}: ${value};`);
}
for (const [name, value] of Object.entries(raw.radius)) {
  cssLines.push(`  --${name}: ${value};`);
}
for (const [name, value] of Object.entries(raw.shadow)) {
  cssLines.push(`  --${name}: ${value};`);
}
for (const [name, t] of Object.entries(raw.type)) {
  cssLines.push(`  --${name}: ${t.size};`);
  cssLines.push(`  --${name}-lh: ${t.lineHeight};`);
}
cssLines.push('}');

// --- Tailwind v4 theme (tokens as CSS vars) --------------------------------
const twLines: string[] = [];
twLines.push('@theme {');
for (const [name, hex] of Object.entries(primitives)) {
  twLines.push(`  --color-${name}: ${hex};`);
}
for (const [name, hex] of Object.entries(semanticHex)) {
  twLines.push(`  --color-${name}: ${hex};`);
}
for (const [name, value] of Object.entries(raw.spacing)) {
  twLines.push(`  --spacing-${name.replace('space-', '')}: ${value};`);
}
twLines.push('}');

const css = `/* GENERATED by @kairo/tokens — do not edit. Source: tokens.json (RFC-001) */\n${cssLines.join('\n')}\n\n${twLines.join('\n')}\n`;
writeFileSync(join(outDir, 'tokens.css'), css);

// --- TypeScript constants ----------------------------------------------------
const ts = `/**
 * GENERATED by @kairo/tokens — do not edit. Source: tokens.json (RFC-001)
 */
export const primitives = ${JSON.stringify(primitives, null, 2)} as const;

export const semantic = ${JSON.stringify(semanticHex, null, 2)} as const;

export const colors = { ...primitives, ...semanticHex } as const;

export const spacing = ${JSON.stringify(raw.spacing, null, 2)} as const;

export const motion = ${JSON.stringify(raw.motion, null, 2)} as const;

export const type = ${JSON.stringify(raw.type, null, 2)} as const;

export const radius = ${JSON.stringify(raw.radius, null, 2)} as const;

export const dataGradient = ${JSON.stringify(raw.dataGradient.map(resolvePrimitive), null, 2)} as const;

export type ColorToken = keyof typeof colors;
`;
writeFileSync(join(outDir, 'tokens.ts'), ts);

console.log('tokens: wrote dist/tokens.css + dist/tokens.ts');
